language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - pip install -r req.txt
  - pip install .
# command to run tests
script:
  - cd test
  - pytest
# safelist
branches:
  only:
  - master
